// 100 Blog-Themen für Holocron Data
// Gleichmäßig auf 4 Säulen verteilt

const topics = [

  // SÄULE 1: DATEN VERSTEHEN (25 Themen) → Insight-Paket
  { id: 1, category: "Daten verstehen", title: "Warum viele Unternehmen nicht wissen, was ihre Daten wirklich wert sind" },
  { id: 2, category: "Daten verstehen", title: "Wann ist der richtige Zeitpunkt für eine BI-Lösung im Mittelstand?" },
  { id: 3, category: "Daten verstehen", title: "Datensilos: Wie getrennte Systeme Entscheidungen verlangsamen" },
  { id: 4, category: "Daten verstehen", title: "Was ist ein Daten-Audit — und warum lohnt er sich vor jedem BI-Projekt?" },
  { id: 5, category: "Daten verstehen", title: "KPIs definieren: Warum die meisten Kennzahlen im Unternehmen falsch gemessen werden" },
  { id: 6, category: "Daten verstehen", title: "Rohdaten vs. aufbereitete Daten: Der Unterschied, der alles verändert" },
  { id: 7, category: "Daten verstehen", title: "Warum drei Abteilungen drei verschiedene Umsatzzahlen haben können" },
  { id: 8, category: "Daten verstehen", title: "Datenqualität messen: Welche Fragen man sich zu Beginn stellen sollte" },
  { id: 9, category: "Daten verstehen", title: "Was kostet schlechte Datenqualität ein Unternehmen wirklich?" },
  { id: 10, category: "Daten verstehen", title: "ERP-Daten nutzbar machen: Wo der Einstieg am sinnvollsten ist" },
  { id: 11, category: "Daten verstehen", title: "Warum Reporting-Probleme selten ein Tool-Problem sind" },
  { id: 12, category: "Daten verstehen", title: "Die häufigsten Missverständnisse über Business Intelligence im Mittelstand" },
  { id: 13, category: "Daten verstehen", title: "Welche Daten ein Unternehmen tatsächlich braucht — und welche nicht" },
  { id: 14, category: "Daten verstehen", title: "Datenstrategie für den Mittelstand: Wo anfangen, wenn alles dringend wirkt?" },
  { id: 15, category: "Daten verstehen", title: "Warum der erste Schritt zu besseren Reports oft kein Dashboard ist" },
  { id: 16, category: "Daten verstehen", title: "Stammdaten vs. Bewegungsdaten: Ein Unterschied mit großer Wirkung" },
  { id: 17, category: "Daten verstehen", title: "Was passiert, wenn niemand im Unternehmen die Daten wirklich versteht?" },
  { id: 18, category: "Daten verstehen", title: "Datenverantwortung: Wer im Unternehmen für Datenqualität zuständig sein sollte" },
  { id: 19, category: "Daten verstehen", title: "Warum viele BI-Projekte scheitern — und wie man es von Anfang an richtig macht" },
  { id: 20, category: "Daten verstehen", title: "Der Unterschied zwischen Daten haben und Daten verstehen" },
  { id: 21, category: "Daten verstehen", title: "Wie man herausfindet, ob die eigenen Daten vertrauenswürdig sind" },
  { id: 22, category: "Daten verstehen", title: "Warum Excel-Berichte oft mehr Fragen aufwerfen als sie beantworten" },
  { id: 23, category: "Daten verstehen", title: "Datenlandschaft dokumentieren: Warum es sich lohnt, bevor man baut" },
  { id: 24, category: "Daten verstehen", title: "Was ein Geschäftsführer wirklich über seine Daten wissen sollte" },
  { id: 25, category: "Daten verstehen", title: "Von Bauchgefühl zu Datenbasis: Was der Umstieg konkret bedeutet" },

  // SÄULE 2: DATEN BEREINIGEN (25 Themen) → Insight / Build-Paket
  { id: 26, category: "Daten bereinigen", title: "Die 5 häufigsten Fehler in Excel-basierten Reportings" },
  { id: 27, category: "Daten bereinigen", title: "Warum Excel kein Datenmodell ist — und was das für Ihr Reporting bedeutet" },
  { id: 28, category: "Daten bereinigen", title: "Doppelte Datensätze: Wie sie entstehen und wie man sie systematisch bereinigt" },
  { id: 29, category: "Daten bereinigen", title: "Inkonsistente Schreibweisen in Kundendaten: Ein unterschätztes Problem" },
  { id: 30, category: "Daten bereinigen", title: "Fehlende Werte in Datensätzen: Ignorieren, ersetzen oder kennzeichnen?" },
  { id: 31, category: "Daten bereinigen", title: "Wie Power Query die Datenbereinigung strukturiert und wiederholbar macht" },
  { id: 32, category: "Daten bereinigen", title: "Datumsformate in Excel: Warum sie so oft Probleme machen" },
  { id: 33, category: "Daten bereinigen", title: "Datenbereinigung dokumentieren: Warum Nachvollziehbarkeit wichtiger ist als Geschwindigkeit" },
  { id: 34, category: "Daten bereinigen", title: "Wenn Quelldaten fehlerhaft sind: Wie man mit dem Problem umgeht ohne die Quelle zu ändern" },
  { id: 35, category: "Daten bereinigen", title: "Warum Datenbereinigung kein einmaliges Projekt ist" },
  { id: 36, category: "Daten bereinigen", title: "Zahlen als Text gespeichert: Ein klassisches Excel-Problem und seine Lösung" },
  { id: 37, category: "Daten bereinigen", title: "Wie man eine Datenbereinigung strukturiert angeht — Schritt für Schritt" },
  { id: 38, category: "Daten bereinigen", title: "Referenzlisten als Grundlage sauberer Daten: Was Lookup-Tabellen leisten" },
  { id: 39, category: "Daten bereinigen", title: "Warum saubere Rohdaten wichtiger sind als ein schönes Dashboard" },
  { id: 40, category: "Daten bereinigen", title: "Outlier in Datensätzen: Fehler oder wertvolle Information?" },
  { id: 41, category: "Daten bereinigen", title: "Wie man Excel-Daten auf Plausibilität prüft, bevor man sie weiterverarbeitet" },
  { id: 42, category: "Daten bereinigen", title: "CSV-Dateien richtig importieren: Häufige Fehlerquellen und wie man sie vermeidet" },
  { id: 43, category: "Daten bereinigen", title: "Daten aus mehreren Quellen zusammenführen: Worauf es dabei ankommt" },
  { id: 44, category: "Daten bereinigen", title: "Warum eine Datenbasis, die 'gut genug' ist, oft nicht gut genug ist" },
  { id: 45, category: "Daten bereinigen", title: "Spaltenstrukturen vereinheitlichen: Wie man heterogene Datenquellen harmonisiert" },
  { id: 46, category: "Daten bereinigen", title: "Wie viel Datenbereinigung ist genug? Eine pragmatische Einschätzung" },
  { id: 47, category: "Daten bereinigen", title: "Automatisierte Datenprüfung: Wann es sich lohnt, Validierungsregeln einzubauen" },
  { id: 48, category: "Daten bereinigen", title: "Warum Datenbereinigung Fachkenntnis braucht — nicht nur technisches Wissen" },
  { id: 49, category: "Daten bereinigen", title: "Bereinigung vs. Transformation: Was der Unterschied ist und warum er zählt" },
  { id: 50, category: "Daten bereinigen", title: "Wie man erkennt, ob eine Datenquelle grundsätzlich unbrauchbar ist" },

  // SÄULE 3: MODELLE & REPORTS (25 Themen) → Build-Paket
  { id: 51, category: "Modelle & Reports", title: "Star Schema erklärt: Warum die Struktur wichtiger ist als das Tool" },
  { id: 52, category: "Modelle & Reports", title: "DAX für Einsteiger: Die 3 Formeln, die man wirklich braucht" },
  { id: 53, category: "Modelle & Reports", title: "Faktentabellen und Dimensionstabellen: Der Kern eines guten Datenmodells" },
  { id: 54, category: "Modelle & Reports", title: "Warum ein Power BI Dashboard ohne Datenmodell wenig wert ist" },
  { id: 55, category: "Modelle & Reports", title: "Wie man ein Power BI Dashboard aufbaut, das wirklich genutzt wird" },
  { id: 56, category: "Modelle & Reports", title: "Beziehungen in Power BI: Häufige Fehler und wie man sie vermeidet" },
  { id: 57, category: "Modelle & Reports", title: "Measures vs. berechnete Spalten in DAX: Wann was sinnvoll ist" },
  { id: 58, category: "Modelle & Reports", title: "Zeitintelligenz in Power BI: Vergleiche zu Vorjahr, Vormonat und YTD richtig umsetzen" },
  { id: 59, category: "Modelle & Reports", title: "Wie man KPIs in Power BI so visualisiert, dass sie sofort verständlich sind" },
  { id: 60, category: "Modelle & Reports", title: "Row-Level Security in Power BI: Wann und wie man Datenzugriff einschränkt" },
  { id: 61, category: "Modelle & Reports", title: "Warum viele Power BI Reports zu viel zeigen — und was man weglassen sollte" },
  { id: 62, category: "Modelle & Reports", title: "Datenmodell-Performance: Warum manche Reports langsam werden und wie man das verhindert" },
  { id: 63, category: "Modelle & Reports", title: "Power Query vs. DAX: Was wohin gehört" },
  { id: 64, category: "Modelle & Reports", title: "Wie man einen Report so gestaltet, dass ihn auch Nicht-Analysten verstehen" },
  { id: 65, category: "Modelle & Reports", title: "Berechnete Tabellen in Power BI: Sinnvoll oder Antipattern?" },
  { id: 66, category: "Modelle & Reports", title: "Warum Drill-Through und Drill-Down in vielen Reports fehlen — und was man damit gewinnt" },
  { id: 67, category: "Modelle & Reports", title: "Datenmodell dokumentieren: Was rein muss, damit andere damit arbeiten können" },
  { id: 68, category: "Modelle & Reports", title: "Wie man Budgetdaten und Ist-Daten in einem Modell sauber zusammenführt" },
  { id: 69, category: "Modelle & Reports", title: "Warum ein Flat Table kein Datenmodell ist — und wann er trotzdem reicht" },
  { id: 70, category: "Modelle & Reports", title: "Farbwahl und Layout in Power BI: Warum Design keine Nebensache ist" },
  { id: 71, category: "Modelle & Reports", title: "Aggregationen in Power BI richtig einsetzen: Was SUMX von SUM unterscheidet" },
  { id: 72, category: "Modelle & Reports", title: "Wie man einen Report-Standard im Unternehmen einführt" },
  { id: 73, category: "Modelle & Reports", title: "Mehrere Datenquellen in einem Modell: Chancen und Fallstricke" },
  { id: 74, category: "Modelle & Reports", title: "Warum Tooltips und Bookmarks in Power BI oft unterschätzt werden" },
  { id: 75, category: "Modelle & Reports", title: "Wie man ein Datenmodell skalierbar aufbaut — von Anfang an" },

  // SÄULE 4: AUTOMATISIERUNG (25 Themen) → Scale-Paket
  { id: 76, category: "Automatisierung", title: "Wie man 8 Stunden manuelle Arbeit pro Monat mit Power BI eliminiert" },
  { id: 77, category: "Automatisierung", title: "Automatischer Datenrefresh in Power BI: Wie er funktioniert und was man beachten muss" },
  { id: 78, category: "Automatisierung", title: "Warum manuelles Reporting ein verstecktes Risiko für Unternehmen ist" },
  { id: 79, category: "Automatisierung", title: "Geplante Datenaktualisierungen: Was man braucht und wie man es einrichtet" },
  { id: 80, category: "Automatisierung", title: "Automatisierter PDF-Export aus Power BI: Möglichkeiten und Grenzen" },
  { id: 81, category: "Automatisierung", title: "Power Automate und Power BI: Wie beide Tools zusammenspielen" },
  { id: 82, category: "Automatisierung", title: "Wann lohnt sich Automatisierung — und wann ist manuell die bessere Wahl?" },
  { id: 83, category: "Automatisierung", title: "Dataflows in Power BI: Datenaufbereitung zentral und wiederverwendbar" },
  { id: 84, category: "Automatisierung", title: "Wie man einen monatlichen Bericht vollständig automatisiert" },
  { id: 85, category: "Automatisierung", title: "Benachrichtigungen bei Schwellenwertüberschreitungen in Power BI einrichten" },
  { id: 86, category: "Automatisierung", title: "Warum Automatisierung ohne saubere Daten nicht funktioniert" },
  { id: 87, category: "Automatisierung", title: "Excel als Datenquelle für Power BI: Wie man es stabil und automatisierbar macht" },
  { id: 88, category: "Automatisierung", title: "Power BI Gateway: Was es ist und wann man es braucht" },
  { id: 89, category: "Automatisierung", title: "Wie man Reporting-Prozesse dokumentiert, damit sie wartbar bleiben" },
  { id: 90, category: "Automatisierung", title: "Automatische Anomalie-Erkennung in Power BI: Was möglich ist" },
  { id: 91, category: "Automatisierung", title: "Warum Automatisierung Governance braucht — und was das konkret bedeutet" },
  { id: 92, category: "Automatisierung", title: "Wie man eine Datenpipeline für den Mittelstand aufbaut ohne IT-Abteilung" },
  { id: 93, category: "Automatisierung", title: "SharePoint als Datenquelle: Möglichkeiten und typische Probleme" },
  { id: 94, category: "Automatisierung", title: "Incremental Refresh in Power BI: Warum er bei großen Datenmengen entscheidend ist" },
  { id: 95, category: "Automatisierung", title: "Wie man automatisierte Reports so gestaltet, dass sie keiner Erklärung bedürfen" },
  { id: 96, category: "Automatisierung", title: "Fehlerbehandlung in automatisierten Prozessen: Was passiert, wenn etwas schiefläuft?" },
  { id: 97, category: "Automatisierung", title: "Von manuell zu automatisiert: Wie ein typischer Migrationsprozess aussieht" },
  { id: 98, category: "Automatisierung", title: "Warum Automatisierung ein Investment ist — und wie man den ROI einschätzt" },
  { id: 99, category: "Automatisierung", title: "SQL als Datenquelle für Power BI: Wann es sich lohnt, direkt zu verbinden" },
  { id: 100, category: "Automatisierung", title: "Wie man sicherstellt, dass automatisierte Reports auch in einem Jahr noch funktionieren" },
];

module.exports = topics;
